### ISSUE TITLE
MineDojo as a new framework

### ISSUE THREAD

**Issue by LinxiFan** [GT-RIPL/Awesome-LLM-Robotics#1]
Thanks for making this Awesome list! We have recently released MineDojo (https://minedojo.org/), a new framework based on Minecraft for developing open-ended, knowledge-intense embodied agents. It isn't directly robotics, but we advocate for the use of foundation models on agent learning, and expect that the algorithms developed with our simulator and database will be generally applicable to other domains. Our paper features a foundation model called MineCLIP that learns an open-vocabulary reward model for multi-task RL.

I think MineDojo could be useful to include in a new "framework" section (?), but would love to hear what you think! 

> MineDojo: Building Open-Ended Embodied Agents with Internet-Scale Knowledge, arXiv, Jun 2022. [[Paper](https://arxiv.org/abs/2206.08853)] [[Website](https://minedojo.org/)] [[Code](https://github.com/MineDojo/MineDojo)] [[Open Database](https://minedojo.org/knowledge_base.html)]

**Comment by zsoltkira** [comment]
I like the idea of adding frameworks enabling the use of such models. I agree it should be in another section though. Are there other frameworks that you think would also fit?

**Comment by LinxiFan** [comment]
Yes, I think other large-scale simulation frameworks to support big embodied agents could be great to add!

Some examples off the top of my head:
* ALFRED: A Benchmark for Interpreting Grounded Instructions for Everyday Tasks. https://arxiv.org/abs/1912.01734
* iGibson 1.0: a Simulation Environment for Interactive Tasks in Large Realistic Scenes. https://arxiv.org/abs/2012.02924
* BEHAVIOR: Benchmark for Everyday Household Activities in Virtual, Interactive, and Ecological Environments. https://arxiv.org/abs/2108.03332

**Comment by zsoltkira** [comment]
Thanks! Those are good, and Habitat (esp [2.0](https://ai.facebook.com/blog/habitat-20-training-home-assistant-robots-with-faster-simulation-and-new-benchmarks/)) would be a good addition as well. 

It's not clear to me how to distinguish simulators/frameworks for large-scale training versus others though. There are lots of simulators/frameworks, and I want to avoid making a laundry list of them here :) 

Did you have thoughts on distinguishing characteristics?

**Comment by wangguanzhi** [comment]
Hi @zsoltkira! I am a student working with @LinxiFan and I just created a [PR](https://github.com/GT-RIPL/Awesome-LLM-Robotics/pull/5) according to the discussion above. Thank you!
