### ISSUE TITLE
Adding two papers: TidyBot, Instruct2Act

### ISSUE THREAD

**Issue by SiyuanHuang95** [GT-RIPL/Awesome-LLM-Robotics#13]
Hi, thanks for your great work!

Do you have a plan to update it timely?

Besides, I would like to add two recent papers: 

**TidyBot**: Personalized Robot Assistance with Large Language Models, arXiv, [Paper](https://arxiv.org/abs/2305.05658) [Code](https://github.com/jimmyyhwu/tidybot/tree/main/robot)

**Instruct2Act**: Mapping Multi-modality Instructions to Robotic Actions with Large Language Model, arXiv, [Paper](https://arxiv.org/pdf/2305.11176.pdf) [Code](https://github.com/OpenGVLab/Instruct2Act)

**Comment by zsoltkira** [comment]
We have been updating based on pull requests. Can you please make one for the paper you mentioned? I will also try to update it based on the many papers having come out in this area.

**Comment by SiyuanHuang95** [comment]
Okay. I will do that PR in the short future.

Anyway, this project did help me a lot to get a quick overview of LLM+Robotics.

**Comment by zsoltkira** [comment]
Great thank you! Glad you found it useful. I also just added a few additional newer ones.
