### ISSUE TITLE
Can we arrange articles in chronological order?

### ISSUE THREAD

**Issue by jacky-ch93** [GT-RIPL/Awesome-LLM-Robotics#24]
Hi！I really like the summary and the continuous tracking of the frontier in this repository! Thank you all for your contribution!
I have a little suggestion that _if we can arrange the paper list in chronological order to keep track of the latest research progress_. Perhaps such a method can make the list more readable.
If you also think so. I can send the pull request to do this work.
Thanks again!

**Comment by jacky-ch93** [comment]
> 

Thanks for your response. I mean that we can also list paper in chronological order even if it is in each sub-categories. This may make it easier to track academic progress over time.

**Comment by zsoltkira** [comment]
Thanks for the suggestion. I don't think it would be a good idea to maintain two lists though, so unless there is an easy dynamic way where people can select chronological vs. categorized I'm not sure this is feasible.
