### ISSUE TITLE
Please add "Where are we in the search for an Artificial Visual Cortex for Embodied Intelligence?"

### ISSUE THREAD

**Issue by asuzukosi** [GT-RIPL/Awesome-LLM-Robotics#26]
Add this paper which covers perception, and covers foundational vision models for embodied AI: https://arxiv.org/pdf/2303.18240.pdf

**Comment by zsoltkira** [comment]
Sure can you do a pull request for this?

**Comment by asuzukosi** [comment]
Okay, will do

**Comment by zsoltkira** [comment]
Thank you!
