### ISSUE TITLE
Suggesting add papers: OVSG and LGMCTS

### ISSUE THREAD

**Issue by changhaonan** [GT-RIPL/Awesome-LLM-Robotics#32]
Thank you for your work to propose such summary!  I am suggesting two papers of our recent work combing LLM and Robotics. One is perception and the other in planning.

## Perception
* **OVSG**: "Context-Aware Entity Grounding with Open-Vocabulary 3D Scene Graphs", CoRL, 2023. [[Paper](https://openreview.net/forum?id=cjEI5qXoT0)] [[Code](https://github.com/changhaonan/OVSG)] [[Website](https://ovsg-l.github.io/)]

## Planning

* **LGMCTS**: "LGMCTS: Language-Guided Monte-Carlo Tree Search for Executable Semantic Object Rearrangement", Arxiv, 2023. [[Paper](https://arxiv.org/abs/2309.15821)]

**Comment by zsoltkira** [comment]
Thanks for the suggestions. Can you please do a pull request?

**Comment by changhaonan** [comment]
Sure. I will add. Please check.
