### ISSUE TITLE
Sort each category chronologically

### ISSUE THREAD

**Issue by shaido987** [GT-RIPL/Awesome-LLM-Robotics#39]
Hello,

Thanks for an awesome collection. Would it be possible to sort each category by paper published time? (a similar issue was raised in #24 but appears to involve an additional complete list of the papers).

It appears like papers have been added at the top and the bottom a bit randomly, it would be better if it's consistent (I would suggest the newest paper in each category at the top). I could help fix this with a PR if wanted.

**Comment by zsoltkira** [comment]
Yes, this sounds good! Please submit a PR.
